# -*- coding: utf-8 -*-
"""C_CRIT_THRESHOLD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uh7OyjzDm57wYioK62czmj2j8mKFwl3x
"""

# ============================================================
# FIGURE B: GLOBAL IMMUNO-CHEMOTHERAPY PHASE BOUNDARY MAP
# Modified Von Bertalanffy + Immune + PK-PD Model
# ============================================================

import numpy as np
import matplotlib.pyplot as plt

from scipy.integrate import solve_ivp


# ============================================================
# 1. MODEL PARAMETERS
# ============================================================

# Tumor growth parameters
a = 0.8
b = 0.02

# Immune parameters
rho = 0.015
s = 0.3
p = 0.5
h = 200.0
delta = 0.2

# Pharmacokinetic parameter
k = 0.7                 # day^-1

# Pharmacodynamic parameters
Emax = 1.5
EC50 = 2.0
n = 2.0

# Initial conditions
V0 = 100.0              # initial tumor volume
E0 = 1.0                # IMPORTANT: E0 = 1
C0 = 0.0

# Final simulation time
T_final = 60.0          # days


# ============================================================
# 2. CRITICAL DRUG CONCENTRATION
# ============================================================

# Hill drug effect:
#
# H(C) = Emax*C^n / (EC50^n + C^n)
#
# Strict eradication condition requires:
#
# H(C) >= 1
#
# Therefore:
#
# Emax*C^n/(EC50^n+C^n) >= 1
#
# Ccrit = EC50 * (1/(Emax-1))^(1/n)

Ccrit = EC50 * (1.0 / (Emax - 1.0))**(1.0 / n)


# ============================================================
# 3. HILL DRUG EFFECT
# ============================================================

def hill_effect(C):

    C = np.maximum(C, 0.0)

    return Emax * C**n / (EC50**n + C**n)


# ============================================================
# 4. EFFECTIVE TUMOR GROWTH COEFFICIENT
# ============================================================

def effective_growth(C):

    H = hill_effect(C)

    return a * (1.0 - H)


# ============================================================
# 5. ODE SYSTEM BETWEEN TWO BOLUSES
# ============================================================

def rhs(t, Y):

    V, E, C = Y

    # Avoid negative values during numerical integration
    V = max(V, 0.0)
    E = max(E, 0.0)
    C = max(C, 0.0)

    # Drug effect
    H = hill_effect(C)

    # Tumor equation
    dVdt = (
        a * (1.0 - H) * V**(2.0 / 3.0)
        - b * V
        - rho * E * V
    )

    # Immune equation
    dEdt = (
        s
        + p * V / (V + h)
        - delta * E
    )

    # PK equation between boluses
    dCdt = -k * C

    return [dVdt, dEdt, dCdt]


# ============================================================
# 6. IMPULSIVE SIMULATION
# ============================================================

def simulate_impulsive(D, tau):

    # Initial condition:
    # First bolus is given at t = 0
    V = V0
    E = E0
    C = D

    t_all = [0.0]
    Y_all = [[V, E, C]]

    current_time = 0.0

    # Number of additional boluses
    n_boluses = int(np.floor(T_final / tau))

    for j in range(1, n_boluses + 1):

        next_time = j * tau

        if next_time > T_final:
            break

        # Integrate until next bolus
        sol = solve_ivp(
            rhs,
            [current_time, next_time],
            [V, E, C],
            method="RK45",
            rtol=1e-7,
            atol=1e-9,
            dense_output=False,
            max_step=0.1
        )

        # Store solution, avoiding duplicate time point
        if len(sol.t) > 1:

            t_all.extend(sol.t[1:])
            Y_all.extend(sol.y.T[1:].tolist())

        # State immediately before bolus
        V = max(sol.y[0, -1], 0.0)
        E = max(sol.y[1, -1], 0.0)
        C = max(sol.y[2, -1], 0.0)

        current_time = next_time

        # Apply bolus:
        #
        # C(t_j+) = C(t_j-) + D
        C = C + D

        # Store post-bolus state
        t_all.append(current_time)
        Y_all.append([V, E, C])

    # Integrate remaining time
    if current_time < T_final:

        sol = solve_ivp(
            rhs,
            [current_time, T_final],
            [V, E, C],
            method="RK45",
            rtol=1e-7,
            atol=1e-9,
            dense_output=False,
            max_step=0.1
        )

        if len(sol.t) > 1:

            t_all.extend(sol.t[1:])
            Y_all.extend(sol.y.T[1:].tolist())

    t_all = np.array(t_all)
    Y_all = np.array(Y_all)

    return t_all, Y_all


# ============================================================
# 7. STEADY-STATE PK TROUGH
# ============================================================

def steady_state_trough(D, tau):

    # For periodic bolus dosing:
    #
    # Cmax = D/(1-exp(-k*tau))
    #
    # Cmin = Cmax*exp(-k*tau)
    #
    # Therefore:
    #
    # Cmin = D/(exp(k*tau)-1)

    denominator = np.exp(k * tau) - 1.0

    if denominator <= 0.0:
        return np.inf

    return D / denominator


# ============================================================
# 8. STRICT THRESHOLD DOSE
# ============================================================

def strict_threshold_dose(tau):

    # Strict eradication:
    #
    # Cmin >= Ccrit
    #
    # D/(exp(k*tau)-1) >= Ccrit
    #
    # Therefore:
    #
    # Dcrit = Ccrit*(exp(k*tau)-1)

    return Ccrit * (np.exp(k * tau) - 1.0)


# ============================================================
# 9. REGIME CLASSIFICATION
# ============================================================

# Regimes:
#
# 0 = Escape
# 1 = Bounded containment
# 2 = Cycle-averaged eradication
# 3 = Strict eradication


def classify_regime(D, tau):

    # --------------------------------------------------------
    # Step 1: Check strict PK threshold
    # --------------------------------------------------------

    Cmin_ss = steady_state_trough(D, tau)

    if Cmin_ss >= Ccrit:

        return 3

    # --------------------------------------------------------
    # Step 2: Numerical simulation
    # --------------------------------------------------------

    t, Y = simulate_impulsive(D, tau)

    V = Y[:, 0]
    E = Y[:, 1]
    C = Y[:, 2]

    V = np.maximum(V, 0.0)
    E = np.maximum(E, 0.0)
    C = np.maximum(C, 0.0)

    # --------------------------------------------------------
    # Consider only the final dosing cycle
    # --------------------------------------------------------

    t_start = max(0.0, T_final - tau)

    mask = t >= t_start

    V_last = V[mask]
    E_last = E[mask]
    C_last = C[mask]

    if len(V_last) < 5:

        return 0

    # --------------------------------------------------------
    # Effective growth during the final cycle
    # --------------------------------------------------------

    eff_growth = effective_growth(C_last)

    mean_eff_growth = np.mean(eff_growth)

    # --------------------------------------------------------
    # Tumor quantities
    # --------------------------------------------------------

    V_start = V_last[0]
    V_end = V_last[-1]
    V_max = np.max(V_last)

    # --------------------------------------------------------
    # Cycle-averaged eradication
    # --------------------------------------------------------

    if V_end < 1e-3:

        return 2

    if V_end < 0.20 * V0 and mean_eff_growth <= 0.0:

        return 2

    # --------------------------------------------------------
    # Bounded containment
    # --------------------------------------------------------

    if V_max < 5.0 * V0:

        if V_end <= 1.05 * V_start:

            return 1

    # --------------------------------------------------------
    # Otherwise: escape
    # --------------------------------------------------------

    return 0


# ============================================================
# 10. BASELINE CALCULATION
# ============================================================

baseline_D = 10.0
baseline_tau = 7.0

baseline_trough = steady_state_trough(
    baseline_D,
    baseline_tau
)

baseline_threshold_dose = strict_threshold_dose(
    baseline_tau
)


print("=" * 65)
print("MODEL PARAMETERS")
print("=" * 65)

print(f"a       = {a}")
print(f"b       = {b}")
print(f"rho     = {rho}")
print(f"s       = {s}")
print(f"p       = {p}")
print(f"h       = {h}")
print(f"delta   = {delta}")
print(f"k       = {k} day^-1")

print(f"Emax    = {Emax}")
print(f"EC50    = {EC50}")
print(f"n       = {n}")

print(f"V0      = {V0}")
print(f"E0      = {E0}")

print(f"Ccrit   = {Ccrit:.4f} mg/L")

print("=" * 65)
print("BASELINE TREATMENT")
print("=" * 65)

print(f"V0      = {V0}")
print(f"E0      = {E0}")
print(f"D       = {baseline_D} mg/L")
print(f"tau     = {baseline_tau} days")
print(f"k       = {k} day^-1")

print(f"Steady-state trough = {baseline_trough:.4f} mg/L")

print(
    f"Strict threshold dose at tau = {baseline_tau} days: "
    f"Dcrit = {baseline_threshold_dose:.4f} mg/L"
)

if baseline_trough >= Ccrit:

    print(
        "Baseline PK condition: "
        "STRICT ERADICATION THRESHOLD SATISFIED."
    )

else:

    print(
        "Baseline PK condition: "
        "Strict eradication threshold NOT satisfied."
    )


# ============================================================
# 11. CHECK BASELINE NUMERICAL SIMULATION
# ============================================================

print("=" * 65)
print("BASELINE NUMERICAL SIMULATION")
print("=" * 65)

t_base, Y_base = simulate_impulsive(
    baseline_D,
    baseline_tau
)

V_base = Y_base[:, 0]
E_base = Y_base[:, 1]
C_base = Y_base[:, 2]

print(f"Final tumor volume = {V_base[-1]:.6f}")
print(f"Final immune level = {E_base[-1]:.6f}")
print(f"Final drug level   = {C_base[-1]:.6f} mg/L")


# ============================================================
# 12. FIGURE B GRID
# ============================================================

# Dose/concentration increment range
D_values = np.linspace(
    1.0,
    400.0,
    80
)

# Dosing interval range in DAYS
tau_values = np.linspace(
    0.5,
    14.0,
    70
)


# ============================================================
# 13. COMPUTE PHASE MAP
# ============================================================

phase_map = np.zeros(
    (len(tau_values), len(D_values)),
    dtype=int
)

print("=" * 65)
print("CALCULATING PHASE MAP")
print("=" * 65)

total = len(tau_values) * len(D_values)
counter = 0

for i, tau in enumerate(tau_values):

    for j, D in enumerate(D_values):

        phase_map[i, j] = classify_regime(
            D,
            tau
        )

        counter += 1

    if (i + 1) % 5 == 0:

        print(
            f"Completed {counter}/{total} calculations"
        )


print("Calculation complete.")


# ============================================================
# 14. PLOT FIGURE B
# ============================================================

plt.figure(
    figsize=(10, 7)
)

plt.imshow(
    phase_map,
    origin="lower",
    aspect="auto",
    extent=[
        D_values.min(),
        D_values.max(),
        tau_values.min(),
        tau_values.max()
    ],
    interpolation="nearest",
    cmap="RdYlGn",
    vmin=0,
    vmax=3
)

# ------------------------------------------------------------
# Critical theoretical threshold boundary
# ------------------------------------------------------------

tau_curve = np.linspace(
    tau_values.min(),
    tau_values.max(),
    400
)

Dcrit_curve = strict_threshold_dose(
    tau_curve
)

# Only show curve inside plotting range
valid = Dcrit_curve <= D_values.max()

plt.plot(
    Dcrit_curve[valid],
    tau_curve[valid],
    "k--",
    linewidth=2.5,
    label="Strict eradication threshold"
)


# ------------------------------------------------------------
# Baseline point
# ------------------------------------------------------------

plt.scatter(
    baseline_D,
    baseline_tau,
    marker="*",
    s=180,
    edgecolor="black",
    linewidth=1.2,
    label="Baseline: D = 10 mg/L, tau = 7 days"
)


# ------------------------------------------------------------
# Labels
# ------------------------------------------------------------

plt.xlabel(
    "Bolus concentration increment ΔC (mg/L)",
    fontsize=12
)

plt.ylabel(
    "Dosing interval τ (days)",
    fontsize=12
)

plt.title(
    "Global Immuno-Chemotherapy Phase Boundary Map",
    fontsize=14
)

cbar = plt.colorbar()

cbar.set_ticks([
    0,
    1,
    2,
    3
])

cbar.set_ticklabels([
    "Escape",
    "Bounded containment",
    "Cycle-averaged eradication",
    "Strict eradication"
])

plt.legend(
    loc="upper right",
    fontsize=9
)

plt.tight_layout()

plt.show()


# ============================================================
# 15. PRINT IMPORTANT THRESHOLD VALUES
# ============================================================

print("=" * 65)
print("IMPORTANT THRESHOLD RESULTS")
print("=" * 65)

print(
    f"Critical concentration Ccrit = "
    f"{Ccrit:.4f} mg/L"
)

print(
    f"For tau = 7 days:"
)

print(
    f"Strict threshold dose Dcrit = "
    f"{baseline_threshold_dose:.4f} mg/L"
)

print(
    f"Baseline D = {baseline_D} mg/L"
)

print(
    f"Baseline tau = {baseline_tau} days"
)

print(
    f"Baseline trough = "
    f"{baseline_trough:.4f} mg/L"
)

if baseline_D >= baseline_threshold_dose:

    print(
        "Baseline lies ABOVE the strict threshold."
    )

else:

    print(
        "Baseline lies BELOW the strict threshold."
    )

print("=" * 65)