# -*- coding: utf-8 -*-
"""CLASSICAL_MODIFIED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xuVFmXBgFiTkiPgfbQlKDizIQq1aavG
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# ============================================================
# PARAMETERS
# ============================================================

a = 0.8          # tumor growth parameter
b = 0.02         # baseline tumor loss rate (day^-1)
gamma = 0.015    # drug effect coefficient

C = 2.0          # constant drug concentration
V0 = 100.0       # initial tumor volume

t_start = 0
t_end = 60
num_points = 1000

t_eval = np.linspace(t_start, t_end, num_points)


# ============================================================
# MODEL 1: CLASSICAL VON BERTALANFFY MODEL
# dV/dt = a*V^(2/3) - b*V
# ============================================================

def model1(t, V):
    dVdt = a * V[0]**(2/3) - b * V[0]
    return [dVdt]


# ============================================================
# MODEL 2: VB MODEL WITH DRUG EFFECT
# dV/dt = a*V^(2/3) - b*V - gamma*C*V
# ============================================================

def model2(t, V):
    dVdt = (
        a * V[0]**(2/3)
        - b * V[0]
        - gamma * C * V[0]
    )
    return [dVdt]


# ============================================================
# SOLVE BOTH MODELS
# ============================================================

solution1 = solve_ivp(
    model1,
    [t_start, t_end],
    [V0],
    t_eval=t_eval,
    rtol=1e-8,
    atol=1e-10
)

solution2 = solve_ivp(
    model2,
    [t_start, t_end],
    [V0],
    t_eval=t_eval,
    rtol=1e-8,
    atol=1e-10
)


# ============================================================
# EXTRACT RESULTS
# ============================================================

V_classical = solution1.y[0]
V_treatment = solution2.y[0]


# ============================================================
# COMPARISON PLOT
# ============================================================

plt.figure(figsize=(10, 6))

plt.plot(
    solution1.t,
    solution1.y[0],
    linewidth=2.5,
    label=r'Without treatment: $aV^{2/3}-bV$'
)

plt.plot(
    solution2.t,
    solution2.y[0],
    '--',
    linewidth=2.5,
    label=r'With treatment: $aV^{2/3}-bV-\gamma C(t)V$'
)

plt.xlabel('Time (days)', fontsize=13)
plt.ylabel('Tumor Volume $V(t)$', fontsize=13)

plt.title(
    'Tumor Growth With and Without Drug Effect',
    fontsize=14
)

# Y-axis: 100 to 1250
plt.ylim(100, 1250)

# Optional: Y-axis ticks
plt.yticks(np.arange(100, 1251, 100))

plt.grid(True, alpha=0.3)
plt.legend(fontsize=11)

plt.tight_layout()
plt.show()