# -*- coding: utf-8 -*-
"""RK4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WnpCgzfuP-3CCa9bV3sVTZ7Qxn6HtQZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ============================================================
# 1. PARAMETERS
# ============================================================

a = 0.8
b = 0.02
rho = 0.015
s = 0.3
p = 0.5
h = 200.0
delta = 0.2
k = 0.7

# Drug effect parameters
Emax = 1.5
EC50 = 2.0
n = 2.0

# Initial conditions
V0 = 100.0
E0 = 1.0
C0 = 0.0

# Simulation
T = 60.0
dt = 0.01

# Bolus dose
bolus = 10.0
dose_times = np.arange(7.0, 57.0, 7.0)


# ============================================================
# 2. DRUG EFFECT
# ============================================================

def gamma(C):

    return (Emax * C**n) / (EC50**n + C**n)


# ============================================================
# 3. MODEL EQUATIONS
# ============================================================

def model_rhs(V, E, C):

    dVdt = (
        a * V**(2.0/3.0)
        - b * V
        - rho * E * V
        - gamma(C) * V
    )

    dEdt = (
        s
        + p * V / (V + h)
        - delta * E
    )

    dCdt = -k * C

    return dVdt, dEdt, dCdt


# ============================================================
# 4. RK4 METHOD
# ============================================================

t = np.arange(0, T + dt, dt)

V = np.zeros(len(t))
E = np.zeros(len(t))
C = np.zeros(len(t))

V[0] = V0
E[0] = E0
C[0] = C0


for i in range(len(t) - 1):

    # --------------------------------------------------------
    # Bolus administration at t = 7,14,...,56
    # --------------------------------------------------------

    if np.any(np.isclose(t[i], dose_times, atol=dt/2)):

        C[i] = C[i] + bolus

    # Current values
    V_i = V[i]
    E_i = E[i]
    C_i = C[i]

    # --------------------------------------------------------
    # k1
    # --------------------------------------------------------

    k1V, k1E, k1C = model_rhs(
        V_i,
        E_i,
        C_i
    )

    # --------------------------------------------------------
    # k2
    # --------------------------------------------------------

    k2V, k2E, k2C = model_rhs(
        V_i + 0.5*dt*k1V,
        E_i + 0.5*dt*k1E,
        C_i + 0.5*dt*k1C
    )

    # --------------------------------------------------------
    # k3
    # --------------------------------------------------------

    k3V, k3E, k3C = model_rhs(
        V_i + 0.5*dt*k2V,
        E_i + 0.5*dt*k2E,
        C_i + 0.5*dt*k2C
    )

    # --------------------------------------------------------
    # k4
    # --------------------------------------------------------

    k4V, k4E, k4C = model_rhs(
        V_i + dt*k3V,
        E_i + dt*k3E,
        C_i + dt*k3C
    )

    # --------------------------------------------------------
    # RK4 update
    # --------------------------------------------------------

    V[i+1] = V_i + (
        dt/6.0
    ) * (
        k1V + 2*k2V + 2*k3V + k4V
    )

    E[i+1] = E_i + (
        dt/6.0
    ) * (
        k1E + 2*k2E + 2*k3E + k4E
    )

    C[i+1] = C_i + (
        dt/6.0
    ) * (
        k1C + 2*k2C + 2*k3C + k4C
    )

    # Avoid negative values
    V[i+1] = max(V[i+1], 0)
    E[i+1] = max(E[i+1], 0)
    C[i+1] = max(C[i+1], 0)


# ============================================================
# FIGURE 1 — TUMOR VOLUME
# ============================================================

plt.figure(figsize=(9, 6))

plt.plot(
    t,
    V,
    linewidth=2
)

# Mark treatment times
for td in dose_times:
    plt.axvline(
        td,
        linestyle="--",
        alpha=0.25
    )

plt.xlabel(
    "Time (days)",
    fontsize=12
)

plt.ylabel(
    r"Tumor volume $V(t)$ (mm$^3$)",
    fontsize=12
)

plt.title(
    "Tumor Volume Dynamics under Repeated Bolus Treatment",
    fontsize=13
)

plt.grid(
    True,
    alpha=0.3
)

plt.tight_layout()

plt.savefig(
    "Figure_C1_Tumor_Volume.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# FIGURE 2 — IMMUNE CELLS
# ============================================================

plt.figure(figsize=(9, 6))

plt.plot(
    t,
    E,
    linewidth=2
)

for td in dose_times:
    plt.axvline(
        td,
        linestyle="--",
        alpha=0.25
    )

plt.xlabel(
    "Time (days)",
    fontsize=12
)

plt.ylabel(
    r"Immune cells $E(t)$ ($10^6$ cells)",
    fontsize=12
)

plt.title(
    "Immune-Cell Dynamics",
    fontsize=13
)

plt.grid(
    True,
    alpha=0.3
)

plt.tight_layout()

plt.savefig(
    "Figure_C2_Immune_Cells.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# FIGURE 3 — DRUG CONCENTRATION
# ============================================================

plt.figure(figsize=(9, 6))

plt.plot(
    t,
    C,
    linewidth=2
)

# Mark bolus times
for td in dose_times:
    plt.axvline(
        td,
        linestyle="--",
        alpha=0.25
    )

plt.xlabel(
    "Time (days)",
    fontsize=12
)

plt.ylabel(
    r"Drug concentration $C(t)$ (mg/L)",
    fontsize=12
)

plt.title(
    "Drug Concentration under Repeated Bolus Administration",
    fontsize=13
)

plt.grid(
    True,
    alpha=0.3
)

plt.tight_layout()

plt.savefig(
    "Figure_C3_Drug_Concentration.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# TABLE 3
# ============================================================

report_times = [
    0, 7, 14, 21, 28,
    35, 42, 49, 56, 60
]

results = []

for tt in report_times:

    index = int(round(tt/dt))

    results.append([
        tt,
        V[index],
        E[index],
        C[index]
    ])


Table3 = pd.DataFrame(
    results,
    columns=[
        "Time (days)",
        "Tumor volume V (mm^3)",
        "Immune cells E (10^6 cells)",
        "Drug concentration C (mg/L)"
    ]
)

print("\nTABLE 3")
print("="*80)

print(
    Table3.to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)


# Save Table 3
Table3.to_csv(
    "Table_3_RK4_results.csv",
    index=False
)

Table3.to_excel(
    "Table_3_RK4_results.xlsx",
    index=False
)

print("\nSimulation completed successfully.")
print("Three separate figures have been generated.")