# -*- coding: utf-8 -*-
"""Structural_Identifiability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdpttsHFOEsq4J3GbuP6VUnvu42jVE3c
"""

# Commented out IPython magic to ensure Python compatibility.
# %% STRUCTURAL IDENTIFIABILITY ANALYSIS
# % Observation: V(t) ONLY
# % Model:
# %
# % dV/dt = a*V^(2/3) - b*V - rho*E*V
# %
# % dE/dt = s + p*V/(V+h) - delta*E
# 
# clear;
# clc;
# 
# %% Symbolic variables
# 
# syms V V1 V2 V3 V4 real
# syms a b rho s p h delta E real
# 
# %% Model equations
# 
# fV = a*V^(2/3) - b*V - rho*E*V;
# 
# fE = s + p*V/(V+h) - delta*E;
# 
# %% Solve the V equation for E
# 
# E_expr = solve(V1 == fV, E);
# 
# disp('E expressed in terms of V and V'' :');
# pretty(E_expr)
# 
# %% Differentiate E with respect to time
# % E = E(V,V')
# 
# dE_dV  = diff(E_expr,V);
# dE_dV1 = diff(E_expr,V1);
# 
# E1_expr = dE_dV*V1 + dE_dV1*V2;
# 
# %% Substitute the immune equation
# 
# eq1 = simplify(E1_expr - ...
#     (s + p*V/(V+h) - delta*E_expr));
# 
# disp('Input-output equation:');
# pretty(eq1)
# 
# %% Clear denominators
# 
# eq1_poly = simplify(together(eq1));
# 
# disp('Simplified input-output equation:');
# pretty(eq1_poly)
# 
# %% Collect terms according to parameters
# 
# disp('Collected expression:');
# collect(eq1_poly,[a b rho s p h delta])
# 
# %% Numerical rank test for parameter combinations
# 
# params = [a b rho s p h delta];
# 
# disp(' ');
# disp('Parameters considered:');
# disp(params);
# 
# %% Jacobian of input-output equation with respect to parameters
# 
# J = jacobian(eq1_poly,params);
# 
# disp('Jacobian:');
# disp(J);
# 
# %% Determine symbolic rank
# 
# R = rank(J);
# 
# fprintf('\nSymbolic/numerical Jacobian rank = %d\n',R);
# 
# fprintf(['\nNumber of original parameters = %d\n'],length(params));
# 
# fprintf(['Maximum number of independently identifiable parameter ' ...
#          'combinations from V(t) = %d\n'],R);

# ================================================================
# STRUCTURAL IDENTIFIABILITY ANALYSIS FROM V(t) ONLY
#
# Model:
#   dV/dt = a*V^(2/3) - b*V - rho*E*V
#
#   dE/dt = s + p*V/(V+h) - delta*E
#
# Observation: V(t) ONLY
#
# This code:
#   1. Eliminates E
#   2. Derives the V-only input-output equation
#   3. Simplifies the equation
#   4. Introduces identifiable parameter combinations
#   5. Performs a generic numerical Jacobian-rank test
# ================================================================

import sympy as sp
import numpy as np

sp.init_printing()

print("="*70)
print("STRUCTURAL IDENTIFIABILITY ANALYSIS: V(t) ONLY")
print("="*70)

# ---------------------------------------------------------------
# 1. SYMBOLIC VARIABLES
# ---------------------------------------------------------------

V, V1, V2 = sp.symbols('V V1 V2', positive=True)

a, b, rho, s, p, h, delta = sp.symbols(
    'a b rho s p h delta',
    nonzero=True
)

print("\nOriginal parameters:")
print("[a, b, rho, s, p, h, delta]")


# ---------------------------------------------------------------
# 2. ORIGINAL V EQUATION
# ---------------------------------------------------------------

# V1 = dV/dt
#
# V1 = a V^(2/3) - bV - rho E V

# Solve for E:

E_expr = sp.solve(
    sp.Eq(
        V1,
        a*V**sp.Rational(2,3) - b*V - rho*sp.Symbol('E')*V
    ),
    sp.Symbol('E')
)[0]

E_expr = sp.simplify(E_expr)

print("\n" + "-"*70)
print("STEP 1: Eliminate the unobserved variable E")
print("-"*70)

print("\nE =")
sp.pprint(E_expr)


# ---------------------------------------------------------------
# 3. CALCULATE dE/dt
# ---------------------------------------------------------------

# E = E(V,V1)
#
# dE/dt =
#       dE/dV * dV/dt
#     + dE/dV1 * d2V/dt2
#
# Therefore:
#
# dE/dt = E_V * V1 + E_V1 * V2

E_V = sp.diff(E_expr, V)
E_V1 = sp.diff(E_expr, V1)

dE_dt = sp.simplify(
    E_V*V1 + E_V1*V2
)

print("\n" + "-"*70)
print("STEP 2: Calculate dE/dt after eliminating E")
print("-"*70)

print("\ndE/dt =")
sp.pprint(dE_dt)


# ---------------------------------------------------------------
# 4. IMMUNE EQUATION
# ---------------------------------------------------------------

# dE/dt = s + pV/(V+h) - delta E

immune_rhs = (
    s
    + p*V/(V+h)
    - delta*E_expr
)


# ---------------------------------------------------------------
# 5. V-ONLY INPUT-OUTPUT EQUATION
# ---------------------------------------------------------------

IO_eq = sp.simplify(
    dE_dt - immune_rhs
)

print("\n" + "="*70)
print("STEP 3: V-ONLY INPUT-OUTPUT EQUATION")
print("="*70)

print("\nEquation:")
sp.pprint(IO_eq)


# ---------------------------------------------------------------
# 6. EXPAND / COLLECT
# ---------------------------------------------------------------

IO_together = sp.factor(
    sp.together(IO_eq)
)

print("\n" + "-"*70)
print("STEP 4: Simplified V-ONLY equation")
print("-"*70)

sp.pprint(IO_together)


# ---------------------------------------------------------------
# 7. MULTIPLY BY rho
#
# This makes the parameter combinations easier to see.
# ---------------------------------------------------------------

IO_rho = sp.simplify(
    sp.expand(rho*IO_eq)
)

print("\n" + "-"*70)
print("STEP 5: Equation multiplied by rho")
print("-"*70)

sp.pprint(IO_rho)


# ---------------------------------------------------------------
# 8. COLLECT PARAMETER TERMS
# ---------------------------------------------------------------

print("\n" + "-"*70)
print("STEP 6: Collected parameter form")
print("-"*70)

IO_collected = sp.collect(
    sp.expand(IO_rho),
    [a, b, rho*s, rho*p, delta, h]
)

sp.pprint(IO_collected)


# ---------------------------------------------------------------
# 9. MANUAL REPARAMETERIZATION
#
# Define:
#
#     q_s = rho*s
#     q_p = rho*p
#
# ---------------------------------------------------------------

q_s, q_p = sp.symbols('q_s q_p')

IO_ident = IO_rho.subs({
    rho*s: q_s,
    rho*p: q_p
})

IO_ident = sp.simplify(IO_ident)

print("\n" + "="*70)
print("STEP 7: IDENTIFIABLE PARAMETERIZATION")
print("="*70)

print("\nDefine:")
print("    q_s = rho*s")
print("    q_p = rho*p")

print("\nThen the V-only equation becomes:")

sp.pprint(IO_ident)


# ---------------------------------------------------------------
# 10. SHOW THE EXPLICIT INPUT-OUTPUT EQUATION
# ---------------------------------------------------------------

print("\n" + "="*70)
print("EXPLICIT V-ONLY INPUT-OUTPUT EQUATION")
print("="*70)

print("""
Using V1 = dV/dt and V2 = d²V/dt²:

       -a/(3 V^(4/3)) * V1
       - V2/V
       + V1²/V²

       = rho*s
         + rho*p*V/(V+h)
         - delta*(a/V^(1/3) - b - V1/V)
""")

# Verify this symbolic form:

IO_explicit = (
    -a/(3*V**sp.Rational(4,3))*V1
    - V2/V
    + V1**2/V**2
    - rho*s
    - rho*p*V/(V+h)
    + delta*(a/V**sp.Rational(1,3) - b - V1/V)
)

verification = sp.simplify(
    IO_eq - IO_explicit
)

print("\nSymbolic verification of the equation:")
print("Difference =", verification)


# ---------------------------------------------------------------
# 11. IDENTIFIABLE COMBINATIONS
# ---------------------------------------------------------------

print("\n" + "="*70)
print("IDENTIFIABILITY RESULT")
print("="*70)

print("""
From V(t) alone, the following combinations appear:

    a
    b
    delta
    h
    rho*s
    rho*p

Therefore use the reparameterized vector:

    theta_V = [a, b, delta, h, rho*s, rho*p]
""")


# ---------------------------------------------------------------
# 12. NON-IDENTIFIABLE INDIVIDUAL PARAMETERS
# ---------------------------------------------------------------

print("-"*70)
print("NON-IDENTIFIABLE INDIVIDUAL PARAMETERS")
print("-"*70)

print("""
rho : NOT separately identifiable
s   : NOT separately identifiable
p   : NOT separately identifiable

Only:

    rho*s

and

    rho*p

can be identified from V(t) alone.
""")


# ---------------------------------------------------------------
# 13. NUMERICAL JACOBIAN RANK TEST
#
# We test the original seven parameters.
# ---------------------------------------------------------------

theta_original = [a, b, rho, s, p, h, delta]

J_original = sp.Matrix(
    [IO_rho]
).jacobian(theta_original)

print("="*70)
print("NUMERICAL JACOBIAN RANK TEST")
print("="*70)

print("\nNumber of original parameters =", len(theta_original))

# Convert symbolic Jacobian to numerical function
J_func = sp.lambdify(
    (
        a, b, rho, s, p, h, delta,
        V, V1, V2
    ),
    J_original,
    'numpy'
)

# ---------------------------------------------------------------
# 14. GENERIC NUMERICAL TESTS
# ---------------------------------------------------------------

np.random.seed(12345)

ranks = []

for i in range(20):

    values = [
        0.5 + np.random.rand(),   # a
        0.1 + np.random.rand(),   # b
        0.5 + np.random.rand(),   # rho
        0.2 + np.random.rand(),   # s
        0.5 + np.random.rand(),   # p
        0.5 + np.random.rand(),   # h
        0.1 + np.random.rand(),   # delta
        0.5 + 2*np.random.rand(), # V
        -1 + 2*np.random.rand(),  # V1
        -1 + 2*np.random.rand()   # V2
    ]

    J_num = np.array(
        J_func(*values),
        dtype=float
    )

    r = np.linalg.matrix_rank(J_num)

    ranks.append(r)


print("\nRanks obtained from 20 generic parameter points:")
print(ranks)

print("\nMaximum generic rank =", max(ranks))

print("\nNumber of original parameters = 7")

if max(ranks) < 7:
    print("""
Conclusion:
The seven original parameters are NOT independently
identifiable from V(t) alone.
""")
else:
    print("""
The numerical rank is 7. Further differential-algebra
analysis is required to confirm full structural identifiability.
""")


# ---------------------------------------------------------------
# 15. JACOBIAN FOR REPARAMETERIZED PARAMETERS
# ---------------------------------------------------------------

theta_ident = [a, b, delta, h, q_s, q_p]

J_ident = sp.Matrix(
    [IO_ident]
).jacobian(theta_ident)

print("="*70)
print("REPARAMETERIZED MODEL")
print("="*70)

print("\nIdentifiable parameter vector:")

sp.pprint(
    sp.Matrix(theta_ident)
)

print("""
These correspond to:

    a
    b
    delta
    h
    q_s = rho*s
    q_p = rho*p
""")


# ---------------------------------------------------------------
# 16. FINAL AUTOMATIC REPORT
# ---------------------------------------------------------------

print("\n" + "="*70)
print("FINAL REPORT FOR V(t)-ONLY DATA")
print("="*70)

print("""
OBSERVATION:
    V(t) only

UNOBSERVED STATE:
    E(t)

ORIGINAL PARAMETERS:
    a, b, rho, s, p, h, delta

IDENTIFIABLE PARAMETERIZATION:
    [a, b, delta, h, rho*s, rho*p]

NON-IDENTIFIABLE INDIVIDUAL PARAMETERS:
    rho
    s
    p

IDENTIFIABLE COMBINATIONS:
    rho*s
    rho*p

Therefore, fitting all seven original parameters independently
to V(t)-only data is not structurally justified.

A suitable V-only parameterization is:

    theta_V = [a, b, delta, h, rho*s, rho*p]
""")

print("="*70)
print("ANALYSIS COMPLETE")
print("="*70)

!wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.9-linux-x86_64.tar.gz
!tar -xzf julia-1.10.9-linux-x86_64.tar.gz
!ln -s /content/julia-1.10.9/bin/julia /usr/local/bin/julia
!julia --version